apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: metriques
  name: metriques
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metriques
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/lab3-default: "true"
        io.kompose.service: metriques
    spec:
      containers:
        - env:
            - name: GITHUB_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: GITHUB_TOKEN
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
          image: elynefdc/metrics:latest
          name: conteneur-metriques
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: "250Mi"
              cpu: "250m"
            requests:
              memory: "250Mi"
              cpu: "250m"          
      restartPolicy: Always
status: {}
