## To implement

//Linter
repos:
  - repo: https://github.com/pycqa/pylint
    rev: v3.0.1
    hooks:
      - id: pylint
        args: [--disable=all]

  - repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
      - id: black

  
  - repo: local
    hooks:
      - id: unit test
        name: unit test
        entry: /test/test.py -m pytest
        language: system
        types: [python]
        pass_filenames: false
