version: "3.8"
services:
  postgres:
    container_name: postgres-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_oxygen
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  app:
    build: ./Dockerfile  # Chemin vers le Dockerfile
    container_name: oxygen-cs
    image: ${DOCKERHUB_USERNAME}/oxygen-cs:latest
    environment :
      HOST: ${HOST}
      TOKEN: ${TOKEN}
      T_MAX: ${T_MAX}
      T_MIN: ${T_MIN}
    ports:
      - "5000:5000"  # Port de l'application Python
