version: "3.7"
services:
  db_postgres2:
    container_name: db_postgres2
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'db_postgres'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin2:
    container_name: pgadmin2
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin:Z
  Metriques:
    container_name: conteneur_metriques
    image: elynefdc/metrics:latest
    restart: always
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "3000:80"
  Oxygene:
    container_name: conteneur_oxygene
    image: elynefdc/oxygen-cs:latest
    restart: always
    ports:
      - "5051:80"
