apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen-cs-deployment
  labels:
    app: oxygen-cs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oxygen-cs
  template:
    metadata:
      labels:
        app: oxygen-cs
    spec:
      containers:
      - name: Oxygen
        image: elynefdc/oxygen-cs:latest
        ports:
        - containerPort: "5051:80"
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
