apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: oxygene
  name: oxygene
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: oxygene
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/lab3-default: "true"
        io.kompose.service: oxygene
    spec:
      containers:
        - env:
            - name: POSTGRES_HOST_OX
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
          image: elynefdc/oxygen-cs:latest
          name: conteneur-oxygene
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "249Mi"
              cpu: "249m"
            requests:
              memory: "249Mi"
              cpu: "249m"          
      restartPolicy: Always
status: {}
