apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: oxygene
  name: oxygene
spec:
  ports:
    - name: "5051"
      port: 5051
      targetPort: 80
  selector:
    io.kompose.service: oxygene
status:
  loadBalancer: {}
