name: CI CD

on:
  push:
    branches:
      - 'elyne-modifcode'
  pull_request:
    types:
      - closed

jobs:
  Build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1-alpine
        env:
          POSTGRES_HOST: postgres
          POSTGRES_DB: db_oxygen
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    
    - name: Load .env file
      run: |
        source .env
        echo "Loaded .env file"
      shell: bash

    - name: Run unit tests
      run: |
        pytest

    - name: Code static analysis and formatting
      run: |
        pip install black
        pip install "pylint==v3.0.2"
        find src -name '*.py' | xargs pylint --fail-under=5
        black src
        
    - name: Prevent push on failure
      if: failure()
      run: exit 1
        
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push app
      uses: docker/build-push-action@v3   
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/oxygen-cs:latest
